#!/bin/bash
# publish-release.sh — Create a Sparkle appcast entry and push a GitHub Release.
#
# Usage:
#   ./scripts/publish-release.sh 1.0.0 1
#
# This assumes:
#   - You have already built the app with `make app MOGU_VERSION=1.0.0 MOGU_BUILD=1`
#   - Your EdDSA private key is in the keychain (generated by Sparkle's generate_keys)
#   - You are authenticated with `gh` for GitHub Releases
#
# What it does:
#   1. Finds Mogu.app in the current directory
#   2. Creates a .dmg (or .zip) from the .app
#   3. Signs the archive with Sparkle's EdDSA key
#   4. Updates appcast.xml with the new release entry
#   5. Pushes the release to GitHub via `gh release create`

set -euo pipefail

VERSION="${1:?Usage: $0 <version> <build>}"
BUILD="${2:?Usage: $0 <version> <build>}"
REPO="AKaLee-IK27/Mogu"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

APP="Mogu.app"
ARCHIVE="Mogu-${VERSION}.zip"
RELEASE_TAG="v${VERSION}"

# ── 1. Find the built app ────────────────────────────────────────────────────
if [[ ! -d "$APP" ]]; then
    echo "Building Mogu.app first..." >&2
    make app "MOGU_VERSION=${VERSION}" "MOGU_BUILD=${BUILD}"
fi

# ── 2. Create the update archive ─────────────────────────────────────────────
rm -f "$ARCHIVE"
ditto -c -k --keepParent "$APP" "$ARCHIVE"
echo "Created ${ARCHIVE}"

# ── 3. Sign with Sparkle EdDSA key ───────────────────────────────────────────
SPARKLE_BIN="$(find .build/artifacts/sparkle/Sparkle -name sign_update -type f 2>/dev/null | head -1)"
if [[ -z "$SPARKLE_BIN" ]]; then
    echo "ERROR: Sparkle's sign_update tool not found. Run 'swift build' first." >&2
    exit 1
fi

SIGN_OUTPUT=$("$SPARKLE_BIN" "$ARCHIVE" 2>&1)
ED_SIGNATURE=$(echo "$SIGN_OUTPUT" | grep -o 'sparkle:edSignature="[^"]*"' | cut -d'"' -f2)
SIGNATURE_LEN=$(echo "$SIGN_OUTPUT" | grep -o 'length="[0-9]*"' | grep -o '[0-9]*')

if [[ -z "$ED_SIGNATURE" || -z "$SIGNATURE_LEN" ]]; then
    echo "ERROR: Failed to sign archive. Output: $SIGN_OUTPUT" >&2
    exit 1
fi

echo "EdDSA signature: ${ED_SIGNATURE:0:20}…"
echo "Archive length:  ${SIGNATURE_LEN}"

# ── 4. Get release notes ─────────────────────────────────────────────────────
RELEASE_NOTES=""
if [[ -f CHANGELOG.md ]]; then
    # Extract notes for this version (between ## header lines)
    RELEASE_NOTES=$(awk "/^## ${VERSION}/{found=1; next} /^##/{found=0} found" CHANGELOG.md)
fi
if [[ -z "$RELEASE_NOTES" ]]; then
    RELEASE_NOTES="See CHANGELOG.md for details."
fi

# ── 5. Create GitHub Release ─────────────────────────────────────────────────
gh release create "$RELEASE_TAG" \
    --title "Mogu ${VERSION}" \
    --notes "$RELEASE_NOTES" \
    "$ARCHIVE"

echo ""
echo "Release ${RELEASE_TAG} published."

# ── 6. Update appcast.xml ────────────────────────────────────────────────────
# The download URL will be the GitHub Release asset URL.
# After the release is created, we can get the URL.
ASSET_URL="https://github.com/${REPO}/releases/download/${RELEASE_TAG}/${ARCHIVE}"

DATE_RFC822=$(date -u "+%a, %d %b %Y %H:%M:%S +0000")

# Build new item XML
ITEM_XML="        <item>
            <title>Version ${VERSION}</title>
            <pubDate>${DATE_RFC822}</pubDate>
            <sparkle:version>${BUILD}</sparkle:version>
            <sparkle:shortVersionString>${VERSION}</sparkle:shortVersionString>
            <sparkle:minimumSystemVersion>14.0</sparkle:minimumSystemVersion>
            <sparkle:releaseNotesLink>https://github.com/${REPO}/releases/tag/${RELEASE_TAG}</sparkle:releaseNotesLink>
            <enclosure
                url=\"${ASSET_URL}\"
                sparkle:edSignature=\"${ED_SIGNATURE}\"
                length=\"${SIGNATURE_LEN}\"
                type=\"application/octet-stream\"
            />
        </item>"

# Update appcast.xml — insert item before </channel>
if [[ -f appcast.xml ]]; then
    sed -i '' "s|</channel>|${ITEM_XML}
    </channel>|" appcast.xml
    echo "Updated appcast.xml"
else
    echo "ERROR: appcast.xml not found" >&2
    exit 1
fi

# ── 7. Push updated appcast.xml ──────────────────────────────────────────────
git add appcast.xml
git commit -m "chore: update appcast for ${VERSION}" || true
echo ""
echo "Done! appcast.xml is ready to commit and push to main."
echo "After pushing, Sparkle will find this update on the next check."
